name: Dependabot workflow

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --production || true
