name: publish package

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
    publish-pkg:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v7
        - uses: actions/setup-node@v6
          with:
            node-version: 24
            registry-url: 'https://npm.pkg.github.com'
            scope: '@biancaichim'
        - run: npm ci
        - name: Run npm publish
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
